GPU_NUM: 1
ac_kwargs:
  act_dim: 2
  conv_channels:
  - 12
  - 4
  - 16
  - 64
  img_h: 84
  img_w: 96
  mlp_channels:
  - 512
  - 128
  - 32
name: ppo
ppo_kwargs:
  adv_norm: false
  clip_ratio: 0.2
  clip_value: false
  data_augument_rate: 0.0
  decay_rate: 0.9
  ent_coef: 0.0
  epochs: 300
  gamma: 0.99
  history_len: 4
  lam: 0.97
  lr_decay: false
  max_ep_len: 1000
  mini_batchsize: 64
  pi_coef: 1
  pi_lr: 0.0003
  schedule_step_size: 100
  seed: 0
  steps_per_epoch: 2048
  target_kl: 0.01
  train_pi_iters: 10
  train_v_iters: 10
  vf_coef: 1
  vf_lr: 0.0005
save_path: null
